#
---

# Set dns forwards
cloud::profile::dns_forwarder::forwarders:
  - '134.76.10.46'
  - '134.76.33.21'

# Zone template
cloud::profile::dns_forwarder::zone_template: &zone
  soa:              'ns1.dev.cloud.gwdg.de'
  soa_email:        'admin.dev.cloud.gwdg.de'
  nameservers:
    - 'ns1'

# Provisioning network A record template
cloud::profile::dns_forwarder::provisioning_record_template: &pr
  zone:             'dev.cloud.gwdg.de'
  ptr:              true

# Define zones
cloud::profile::dns_forwarder::zones:

  'dev.cloud.gwdg.de':
    <<: *zone
  
  "%{hiera('vagrant::in_addr_arpa_private')}.IN-ADDR.ARPA":
    <<: *zone

  "%{hiera('vagrant::in_addr_arpa_public')}.IN-ADDR.ARPA":
    <<: *zone

# Define A records
cloud::profile::dns_forwarder::records:
  
  # Public dns names (pointing to public net)
  'api':
    data:           ["%{hiera('vagrant::ip_prefix')}.100.3"]
    <<: *pr

  # Infrastructure for environment

  'puppetmaster':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.2"]
    <<: *pr

  'nfs':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.6"]
    <<: *pr

  'rally':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.7"]
    <<: *pr

  'ldap':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.8"]
    <<: *pr

  # HAProxy LBs

  # VIPs for loadbalancer (not provisioned)
  # !!! NEEDS CORRECT ZONES !!!
#     'lb-private-vip':   data => ["%{hiera('vagrant::ip_prefix')}.1.3"]
#     'lb-public-vip':    data => ["%{hiera('vagrant::ip_prefix')}.100.3"]

  'lb1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.11"]
    <<: *pr

  'lb2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.12"]
    <<: *pr

  # Logging Node
  'logstash':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.14"]
    <<: *pr

  # Galera cluster

  'galera1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.21"]
    <<: *pr

  'galera2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.22"]
    <<: *pr

  # MongoDB cluster

  'mongo1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.71"]
    <<: *pr

  'mongo2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.72"]
    <<: *pr

  'mongo3':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.73"]
    <<: *pr

  # Controller (+ RabbitMQ)

  'controller1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.31"]
    <<: *pr

  'controller2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.32"]
    <<: *pr

  # Storage nodes

  'storage1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.41"]
    <<: *pr

  'storage2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.42"]
    <<: *pr

  # Network nodes

  'network1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.51"]
    <<: *pr

  'network2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.52"]
    <<: *pr

  # Spof nodes

  'spof1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.61"]
    <<: *pr

  'spof2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.62"]
    <<: *pr

  # Compute nodes

  'compute1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.101"]
    <<: *pr

  'compute2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.102"]
    <<: *pr

  'compute3':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.103"]
    <<: *pr

  # Docker Nodes

  'docker1':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.111"]
    <<: *pr

  'docker2':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.112"]
    <<: *pr

  'docker3':
    data:           ["%{hiera('vagrant::ip_prefix')}.1.113"]
    <<: *pr


  # Legacy stuff, not sure
  # %{hiera('vagrant::ip_prefix')}.1.8      opentsdb.cloud.gwdg.de

  # Swift (unused)
  # %{hiera('vagrant::ip_prefix')}.1.50     swift-proxy.cloud.gwdg.de
  # %{hiera('vagrant::ip_prefix')}.1.51     swift-proxy-s3.cloud.gwdg.de
  # %{hiera('vagrant::ip_prefix')}.1.60     swift-storage1.cloud.gwdg.de
  # %{hiera('vagrant::ip_prefix')}.1.61     swift-storage2.cloud.gwdg.de
  # %{hiera('vagrant::ip_prefix')}.1.62     swift-storage3.cloud.gwdg.de
 

