#
# Loadbalancer setup (haproxy / keepalived)
#
---

cloud::loadbalancer::vip_public_ip:
    - "%{hiera('cloud::global::public_api_vip')}"

cloud::loadbalancer::vip_internal_ip:
    - "%{hiera('cloud::global::internal_api_vip')}"

cloud::loadbalancer::vip_monitor_ip:                            false

cloud::loadbalancer::galera_ip:
    - "%{hiera('cloud::global::internal_api_vip')}"

cloud::loadbalancer::galera_slave:                              false

cloud::loadbalancer::haproxy_ensure:                            "%{hiera('cloud::global::package_ensure')}"

cloud::loadbalancer::haproxy_global_options:

    log:                            "%{hiera('cloud::logging::server::logstash_syslog_bind_ip')}:%{hiera('cloud::logging::server::logstash_syslog_port')} local0"
    maxconn:                        '4096'
   
    # Do not set nbproc (1 worker is best practice vor haproxy)
#    nbproc:                         "%{::processorcount}"

    # SSL related options
    ssl-default-bind-ciphers:       'EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH+aRSA+RC4:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4'
    ssl-default-bind-options:       'no-sslv3 no-tlsv10'
    tune.ssl.default-dh-param:      '4096'

cloud::loadbalancer::haproxy_defaults_options:                  {}

cloud::loadbalancer::haproxy_certs:                             'api.liberty.mikelangelo.gwdg.de_20160118_all.pem'

cloud::loadbalancer::vip_monitor_ip:                            "%{hiera('cloud::global::internal_api_vip')}"

cloud::loadbalancer::haproxy_auth:                              "admin:%{hiera('cloud::global::web_management::password')}"

cloud::loadbalancer::enable_swift_api:                          false
cloud::loadbalancer::enable_ceilometer_api:                     true
cloud::loadbalancer::enable_cinder_api:                         true
cloud::loadbalancer::enable_glance_api:                         true
cloud::loadbalancer::enable_glance_registry:                    true
cloud::loadbalancer::enable_neutron_api:                        true
cloud::loadbalancer::enable_heat_api:                           true
cloud::loadbalancer::enable_heat_cfn_api:                       true
cloud::loadbalancer::enable_heat_cloudwatch_api:                true
cloud::loadbalancer::enable_nova_api:                           true
cloud::loadbalancer::enable_ec2_api:                            true
cloud::loadbalancer::enable_metadata_api:                       true
cloud::loadbalancer::enable_keystone_api:                       true
cloud::loadbalancer::enable_keystone_api_admin:                 true
cloud::loadbalancer::enable_trove_api:                          false
cloud::loadbalancer::enable_horizon:                            true
cloud::loadbalancer::enable_horizon_ssl:                        false
cloud::loadbalancer::enable_rabbitmq:                           true
cloud::loadbalancer::enable_rabbitmq_management:                true
cloud::loadbalancer::enable_spice:                              false
cloud::loadbalancer::enable_novnc:                              true
cloud::loadbalancer::enable_elasticsearch:                      false
cloud::loadbalancer::enable_kibana:                             true
cloud::loadbalancer::enable_logstash_syslog:                    true

# Allow to override HAProxy options
cloud::loadbalancer::ceilometer_options:                        {}                                                                                                                                          
cloud::loadbalancer::cinder_options:                            {}
cloud::loadbalancer::ec2_options:                               {}                                                                                                                                          
cloud::loadbalancer::glance_api_options:                        {}
cloud::loadbalancer::glance_registry_options:                   {}                                                                                                                                          
cloud::loadbalancer::heat_cfn_options:                          {}
cloud::loadbalancer::heat_cloudwatch_options:                   {}
cloud::loadbalancer::heat_api_options:                          {}
cloud::loadbalancer::keystone_options:                          {}
cloud::loadbalancer::keystone_admin_options:                    {}
cloud::loadbalancer::metadata_options:                          {}
cloud::loadbalancer::neutron_options:                           {}
cloud::loadbalancer::nova_options:                              {}
cloud::loadbalancer::trove_options:                             {}
cloud::loadbalancer::swift_options:                             {}
cloud::loadbalancer::spice_options:                             {}
cloud::loadbalancer::novnc_options:                             {}
cloud::loadbalancer::horizon_options:                           {}
cloud::loadbalancer::horizon_ssl_options:                       {}
cloud::loadbalancer::rabbitmq_options:                          {}
cloud::loadbalancer::galera_options:                            {}
cloud::loadbalancer::elasticsearch_options:                     {}
cloud::loadbalancer::kibana_options:                            {}
cloud::loadbalancer::logstash_syslog_options:                   {}

cloud::loadbalancer::ks_ceilometer_public_port:                 "%{hiera('cloud::global::api::ports::ceilometer')}"
cloud::loadbalancer::ks_cinder_public_port:                     "%{hiera('cloud::global::api::ports::cinder')}"
cloud::loadbalancer::ks_ec2_public_port:                        "%{hiera('cloud::global::api::ports::nova_ec2')}"
cloud::loadbalancer::ks_glance_api_public_port:                 "%{hiera('cloud::global::api::ports::glance')}"
cloud::loadbalancer::ks_glance_registry_internal_port:          "%{hiera('cloud::global::api::ports::glance_registry')}"
cloud::loadbalancer::ks_heat_cfn_public_port:                   "%{hiera('cloud::global::api::ports::heat_cfn')}"
cloud::loadbalancer::ks_heat_cloudwatch_public_port:            "%{hiera('cloud::global::api::ports::heat_cloudwatch')}"
cloud::loadbalancer::ks_heat_public_port:                       "%{hiera('cloud::global::api::ports::heat')}"
cloud::loadbalancer::ks_keystone_admin_port:                    "%{hiera('cloud::global::api::ports::keystone_admin')}"
cloud::loadbalancer::ks_keystone_public_port:                   "%{hiera('cloud::global::api::ports::keystone')}"
cloud::loadbalancer::ks_metadata_public_port:                   "%{hiera('cloud::global::api::ports::nova_metadata')}"
cloud::loadbalancer::ks_neutron_public_port:                    "%{hiera('cloud::global::api::ports::neutron')}"
cloud::loadbalancer::ks_nova_public_port:                       "%{hiera('cloud::global::api::ports::nova')}"
cloud::loadbalancer::ks_swift_public_port:                      "%{hiera('cloud::global::api::ports::swift')}"
cloud::loadbalancer::ks_trove_public_port:                      "%{hiera('cloud::global::api::ports::trove')}"
cloud::loadbalancer::rabbitmq_port:                             "%{hiera('cloud::global::api::ports::rabbitmq')}"
cloud::loadbalancer::rabbitmq_management_port:                  "%{hiera('cloud::global::api::ports::rabbitmq_management')}"
cloud::loadbalancer::horizon_port:                              "%{hiera('cloud::global::api::ports::horizon')}"
cloud::loadbalancer::horizon_ssl_port:                          "%{hiera('cloud::global::api::ports::horizon_ssl')}"
cloud::loadbalancer::spice_port:                                "%{hiera('cloud::global::api::ports::spice')}"
cloud::loadbalancer::novnc_port:                                "%{hiera('cloud::global::api::ports::novnc')}"
cloud::loadbalancer::elasticsearch_port:                        '9200'
cloud::loadbalancer::kibana_port:                               "%{hiera('cloud::global::api::ports::kibana')}"
cloud::loadbalancer::logstash_syslog_port:                      "%{hiera('cloud::global::api::ports::logstash_syslog')}"

cloud::loadbalancer::firewall_settings:                         {}

cloud::loadbalancer::vip_internal_network:                      "%{hiera('cloud::global::network::management_network')}"
cloud::loadbalancer::vip_internal_gateway:                      "%{hiera('cloud::global::network::management_gateway')}"

cloud::loadbalancer::vip_public_network:                        "%{hiera('cloud::global::network::public_network')}"
cloud::loadbalancer::vip_public_gateway:                        "%{hiera('cloud::global::network::public_gateway')}"

cloud::loadbalancer::keepalived_state:                          'BACKUP'
cloud::loadbalancer::keepalived_priority:                       50
cloud::loadbalancer::keepalived_preempt_delay:                  30
cloud::loadbalancer::keepalived_vrrp_interface:                 false

cloud::loadbalancer::keepalived_public_interface:               "%{hiera('cloud::global::network::public_interface')}"
cloud::loadbalancer::keepalived_public_ipvs:                    ["%{hiera('cloud::global::public_api_vip')}"]

cloud::loadbalancer::keepalived_internal_interface:             "%{hiera('cloud::global::network::management_interface')}"
cloud::loadbalancer::keepalived_internal_ipvs:                  ["%{hiera('cloud::global::internal_api_vip')}"]

cloud::loadbalancer::keepalived_auth_type:                      false
cloud::loadbalancer::keepalived_auth_pass:                      false

