#
---

cloud::container::log_facility:                      'LOG_LOCAL0'
cloud::container::rabbit_hosts:
  - "%{hiera('cloud::global::controller1::rabbitmq')}"
  - "%{hiera('cloud::global::controller2::rabbitmq')}"
cloud::container::rabbit_password:                   "%{hiera('cloud::global::rabbit::password')}"
cloud::container::magnum_db_user:                    "%{hiera('cloud::global::db::magnum_user')}"
cloud::container::magnum_db_password:                "%{hiera('cloud::global::db::magnum_password')}"
cloud::container::magnum_db_host:                    "%{hiera('cloud::global::db::host')}"

cloud::container::api::ks_magnum_internal_port:      "%{hiera('cloud::global::api::ports::magnum')}"
cloud::container::api::ks_keystone_internal_host:    "%{hiera('cloud::global::internal_api_host')}"
cloud::container::api::ks_keystone_internal_port:    "%{hiera('cloud::global::api::ports::keystone')}"
cloud::container::api::ks_keystone_internal_proto:   "%{hiera('cloud::global::internal_api_proto')}"
cloud::container::api::ks_keystone_admin_port:       "%{hiera('cloud::global::api::ports::keystone_admin')}"
cloud::container::api::ks_magnum_password:           "%{hiera('cloud::global::api::passwords::magnum')}"
cloud::container::api::api_eth:                      "%{hiera('node::management_ip')}"